# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3659bde2d9712e4a13faf1bcc1c728972cf4811a6fe92b8bf82bb38ee878cc2e2c7947379bab4aa0606e57e7968193651ecb9965f58f273568ecc3f2d4a374c

test:
  secret_key_base: 42f6091ddba2df28ff85f4e357d994e85a3ee9c46b26bfec0ed778f30d9702ab48a5687eb8c98c80dd61f11d850eff820fec16943041025093a661bdf53f5655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
